### ISSUE TITLE
error while trying to download anything

### ISSUE THREAD

**Issue by ArekKubinski** [painebenjamin/app.enfugue.ai#112]
Hello, this is a fresh install of OS and enfugue, every option I used was default. I am using conda to run it and every time I am trying to download anything using web interface it throws errors in the terminal that I am running app from

```
(base) pej@pej:~$ conda activate enfugue
(enfugue) pej@pej:~$ enfugue run
Running enfugue, visit at https://app.enfugue.ai:45554/ (press Ctrl+C to exit)
Running enfugue, visit at https://app.enfugue.ai:45554/ (press Ctrl+C to exit)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/manager.py", line 63, in run
    self.manager.do_periodic_tasks()
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/manager.py", line 603, in do_periodic_tasks
    available_downloads = self.remaining_concurrent_downloads
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/manager.py", line 351, in remaining_concurrent_downloads
    return self.max_concurrent_downloads - len(self.active_downloads)
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/manager.py", line 339, in active_downloads
    return [
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/manager.py", line 343, in <listcomp>
    if not download.complete and download.started
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/downloads.py", line 228, in complete
    self.check_raise_exitcode()
  File "/home/pej/anaconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/api/downloads.py", line 155, in check_raise_exitcode
    raise IOError(f"Process died with exit code {self.process.exitcode}")
OSError: Process died with exit code 70
^CGoodbye!
(enfugue) pej@pej:~$ /home/pej/anaconda3/envs/enfugue/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

**Comment by painebenjamin** [comment]
Hello @ArekKubinski, thank you for the report!

There is an issue with the `enfugue run` command that causes subprocesses to fail. I do not have a lot of insight into why, unfortunately - but if you run it instead using `python -m enfugue run`, that seems to rectify the issue. I'm hoping to have this fixed for next release.

Please let me know if this doesn't fix it for you.

**Comment by ArekKubinski** [comment]
Yeah, this fixed things for me, but I still get some warnings in terminal, this time about tensor RT but i run linux-cuda-latest enviroment. I guess this is not that important since everything seems to work but i will include them here just in case :)

```
2023-11-20 20:03:02.366113: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-20 20:03:02.400941: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-20 20:03:02.400983: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-20 20:03:02.401945: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-20 20:03:02.407301: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-20 20:03:02.407462: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-20 20:03:03.018570: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-20 20:03:03.525453: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-20 20:03:03.525877: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

```
