### ISSUE TITLE
Image generation does not work with every LyCORIS (I tested)

### ISSUE THREAD

**Issue by Temder** [painebenjamin/app.enfugue.ai#143]
Every time I add a LyCORIS to a model and click on the generation button I get this error:
![grafik](https://github.com/painebenjamin/app.enfugue.ai/assets/57451447/8570a46b-882d-4a12-8944-45a48ced0cd5)

This is the full log:
![grafik](https://github.com/painebenjamin/app.enfugue.ai/assets/57451447/4ea833c6-5b8a-4cb7-b063-6bf527c8c9cd)

Am I doing something wrong?

**Comment by RocketSmash9000** [comment]
I am getting a similar error, though it happens with loras and lycoris.

```
Traceback (most recent call last):
  File "enfugue\diffusion\process.py", line 199, in run

    response["result"] = self.handle(instruction_id, instruction_action, instruction_payload)

  File "enfugue\diffusion\process.py", line 260, in handle

    return self.execute_diffusion_plan(

  File "enfugue\diffusion\process.py", line 304, in execute_diffusion_plan

    return plan.execute(

  File "enfugue\diffusion\invocation\layers.py", line 1496, in execute

    images, nsfw = self.execute_inference(

  File "enfugue\diffusion\invocation\layers.py", line 1726, in execute_inference

    result = pipeline(

  File "enfugue\diffusion\manager.py", line 5400, in __call__

    pipe = self.pipeline # type: ignore

  File "enfugue\diffusion\manager.py", line 3443, in pipeline

    pipeline.load_lora_weights(lora, multiplier=weight)

  File "enfugue\diffusion\pipeline.py", line 1269, in load_lora_weights

    return self.load_flexible_lora_weights(

  File "enfugue\diffusion\pipeline.py", line 1363, in load_flexible_lora_weights

    state_dict = load_state_dict(pretrained_model_name_or_path_or_dict) # type: ignore[arg-type]

  File "enfugue\diffusion\util\torch_util\model_util.py", line 53, in load_state_dict

    raise IOError(f"Recevied exception reading checkpoint {path}, please ensure file integrity.\n{type(first_error).__name__}: {first_error}")

OSError: Recevied exception reading checkpoint C:\Users\*user*\.cache\enfugue\lora\*nameOfLora*.safetensors, please ensure file integrity.

SafetensorError: Error while deserializing header: HeaderTooLarge
```

What is even weirder is that I could previously run loras perfectly. Now it doesn't want to run anything.
