### ISSUE TITLE
cached_download is no longer part of huggingface as of 0.26

### ISSUE THREAD

**Issue by jacksonkr** [painebenjamin/app.enfugue.ai#150]
When I try to generate an image I recieve `cannot import name 'cached_download' from 'huggingface_hub' (/home/jackson/.local/lib/python3.10/site-packages/huggingface_hub/__init__.py)`

Full traceback:

```
Traceback (most recent call last):
  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/process.py", line 260, in handle

    return self.execute_diffusion_plan(

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/process.py", line 302, in execute_diffusion_plan

    self.pipemanager.keepalive_callback = lambda: progress_callback(0, 0, 0.0)

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/process.py", line 237, in pipemanager

    self._pipemanager = DiffusionPipelineManager(self.configuration, optimize=False)

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/manager.py", line 151, in __init__

    self.apply_patches()

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/manager.py", line 193, in apply_patches

    self.patch_freeu()

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/manager.py", line 201, in patch_freeu

    import diffusers.utils.torch_utils

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in 

    from .configuration_utils import ConfigMixin

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in 

    from .utils import (

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 37, in 

    from .dynamic_modules_utils import get_class_from_dynamic_module

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in 

    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info

ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/jackson/.local/lib/python3.10/site-packages/huggingface_hub/__init__.py)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/process.py", line 199, in run

    response["result"] = self.handle(instruction_id, instruction_action, instruction_payload)

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/process.py", line 281, in handle

    self.pipemanager.stop_keepalive()

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/process.py", line 237, in pipemanager

    self._pipemanager = DiffusionPipelineManager(self.configuration, optimize=False)

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/manager.py", line 151, in __init__

    self.apply_patches()

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/manager.py", line 193, in apply_patches

    self.patch_freeu()

  File "/home/jackson/miniconda3/envs/enfugue/lib/python3.10/site-packages/enfugue/diffusion/manager.py", line 201, in patch_freeu

    import diffusers.utils.torch_utils

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in 

    from .configuration_utils import ConfigMixin

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in 

    from .utils import (

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 37, in 

    from .dynamic_modules_utils import get_class_from_dynamic_module

  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in 

    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info

ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/jackson/.local/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

While tracking down the missing package I found:
https://github.com/huggingface/huggingface_hub/issues/2617

**Comment by painebenjamin** [comment]
Hello,

Thank you for the report. I'm working on a branch right now that updates most packages to their latest versions. There's some mixed compatibility issues I'm working through, you can see progress on the branch at https://github.com/painebenjamin/app.enfugue.ai/tree/0.4.0.
