### ISSUE TITLE
Correct Malformed VAE State Dictionaries when Necessary

### ISSUE THREAD

**Issue by painebenjamin** [painebenjamin/app.enfugue.ai#17]
### Discussed in https://github.com/painebenjamin/app.enfugue.ai/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **Ryuijin5746** June 28, 2023</sup>
I dont know what ive done wrong, but I get an error each time it tries to generate. 

"'encoder.conv_in.weight'"

 i have not tweaked any default settings

![Capture](https://github.com/painebenjamin/app.enfugue.ai/assets/138042985/cd6e0c67-740f-4cdf-af05-b828f835a298)
![Capture2](https://github.com/painebenjamin/app.enfugue.ai/assets/138042985/e7eeca2f-223d-4ea9-be5e-6a53857d24d0)
</div>

**Comment by painebenjamin** [comment]
[Taureal Mix](https://civitai.com/models/63323/taureal-mix)

```
2023-06-28 20:15:19,434 [enfugue] ERROR (engine.py:263) Traceback (most recent call last):
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\process.py", line 328, in run
    response["result"] = self.execute_diffusion_plan(
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\process.py", line 114, in execute_diffusion_plan
    return plan.execute(
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\plan.py", line 587, in execute
    images, nsfw = self.execute_nodes(
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\plan.py", line 743, in execute_nodes
    self.prepare_pipeline(pipeline)
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\plan.py", line 712, in prepare_pipeline
    pipeline.model = self.model
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\manager.py", line 699, in model
    new_model = self.check_convert_checkpoint(new_model)
  File "C:\cygwin64\home\paine\projects\enfugue\src\python\enfugue\diffusion\manager.py", line 1132, in check_convert_checkpoint
    pipe = download_from_original_stable_diffusion_ckpt(
  File "C:\Users\paine\anaconda3\envs\enfugue\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1185, in download_from_original_stable_diffusion_ckpt
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(checkpoint, vae_config)
  File "C:\Users\paine\anaconda3\envs\enfugue\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 580, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'
```
