### ISSUE TITLE
Win10 system, why can’t it be opened?

### ISSUE THREAD

**Issue by Crazy-CYZ** [painebenjamin/app.enfugue.ai#84]
![微信截图_20231005175717](https://github.com/painebenjamin/app.enfugue.ai/assets/89187812/8f72b73b-9d65-4be8-b798-1cff5728402e)

**Comment by Crazy-CYZ** [comment]
@painebenjamin 

**This is the contents of enfugue.log**

2023-10-05 17:16:19,593 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:16:19] ENGINE Bus STARTING
2023-10-05 17:16:19,818 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:16:19] ENGINE Serving on https://0.0.0.0:45554
2023-10-05 17:16:19,820 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:16:19] ENGINE Bus STARTED
2023-10-05 17:18:40,519 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:18:40] ENGINE Bus STARTING
2023-10-05 17:18:40,753 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:18:40] ENGINE Serving on https://0.0.0.0:45554
2023-10-05 17:18:40,753 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:18:40] ENGINE Bus STARTED
2023-10-05 17:22:14,727 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:22:14] ENGINE Bus STARTING
2023-10-05 17:22:15,767 [cherrypy.error] ERROR (_cplogging.py:213) [05/Oct/2023:17:22:15] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x000001A3F38CB4F0>>
Traceback (most recent call last):
  File "portend.py", line 122, in free
  File "portend.py", line 71, in assert_free
  File "portend.py", line 87, in _connect
portend.PortNotFree: Port 45554 is in use on 127.0.0.1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cherrypy\process\wspbus.py", line 230, in publish
  File "cherrypy\_cpserver.py", line 180, in start
  File "cherrypy\process\servers.py", line 177, in start
  File "portend.py", line 126, in free
portend.Timeout: Port 45554 not free on 0.0.0.0.

2023-10-05 17:22:15,768 [cherrypy.error] ERROR (_cplogging.py:213) [05/Oct/2023:17:22:15] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "cherrypy\process\wspbus.py", line 268, in start
  File "cherrypy\process\wspbus.py", line 248, in publish
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 45554 not free on 0.0.0.0.')

2023-10-05 17:22:15,768 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:22:15] ENGINE Bus STOPPING
2023-10-05 17:22:15,769 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:22:15] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 45554)) already shut down
2023-10-05 17:22:15,769 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:22:15] ENGINE Bus STOPPED
2023-10-05 17:22:15,769 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:22:15] ENGINE Bus EXITING
2023-10-05 17:22:16,075 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:22:16] ENGINE Bus EXITED
2023-10-05 17:49:41,833 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:49:41] ENGINE Bus STARTING
2023-10-05 17:49:42,064 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:49:42] ENGINE Serving on https://0.0.0.0:45554
2023-10-05 17:49:42,065 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:49:42] ENGINE Bus STARTED
2023-10-05 17:50:41,204 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:50:41] ENGINE Bus STARTING
2023-10-05 17:50:41,431 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:50:41] ENGINE Serving on https://0.0.0.0:45554
2023-10-05 17:50:41,432 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:50:41] ENGINE Bus STARTED
2023-10-05 17:56:19,566 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:56:19] ENGINE Bus STARTING
2023-10-05 17:56:19,796 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:56:19] ENGINE Serving on https://0.0.0.0:45554
2023-10-05 17:56:19,797 [cherrypy.error] INFO (_cplogging.py:213) [05/Oct/2023:17:56:19] ENGINE Bus STARTED
2023-10-06 09:04:08,943 [cherrypy.error] INFO (_cplogging.py:213) [06/Oct/2023:09:04:08] ENGINE Bus STARTING
2023-10-06 09:04:09,174 [cherrypy.error] INFO (_cplogging.py:213) [06/Oct/2023:09:04:09] ENGINE Serving on https://0.0.0.0:45554
2023-10-06 09:04:09,174 [cherrypy.error] INFO (_cplogging.py:213) [06/Oct/2023:09:04:09] ENGINE Bus STARTED

**Comment by painebenjamin** [comment]
Hello @Crazy-CYZ,

Thankfully the log says the error right away:
`portend.PortNotFree: Port 45554 is in use on 127.0.0.1.`

It looks like some other application is using that port. Sorry about that - you'll need to change it.

In the same directory with `enfugue-server.exe`, open the `enfugue` folder and into `config`. Open the file `server.yml` with a text editor, and locate the line that says `port: 45554`. Change this to a different number greater than 1024 but less than 65535, and then restart the application. Do not modify any spacing in this file other than changing the number.

After that, you'll be able to access the UI at `https://app.enfugue.ai:<your-port-number>`.

**Comment by Crazy-CYZ** [comment]
@painebenjamin 

I found the problem. When I open the agent software v2rayN, I cannot open enfugue. When I close the agent software v2rayN, I can use enfugue.

**Comment by painebenjamin** [comment]
Excellent, glad you found the problem! Thank you for coming back and telling me, too, now I'll know to help the next person who might also use that software.

Thanks again!
